name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
      
          config_display: columns      # Enables column layout
          config_columns: 2            # Set number of columns you want (try 2 or 3)
      
          plugin_lines: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 2%
          plugin_stars: yes
          plugin_followup: yes
          plugin_gists: yes

