name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # runs every hour
  push: { branches: ["main"] }      # or your default branch
  workflow_dispatch:                # allows manual run

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages.colors: github
          plugin_languages.threshold: 2%
          plugin_stars: yes
          plugin_followup: yes
          plugin_gists: yes
