name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }]  # Runs every hour
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Output file
          filename: github-metrics.svg

          # General layout configuration
          config_display: columns
          config_columns: 2
          config_order: base.header, base.activity, community, repositories, metadata

          # Core sections
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_lines: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 2%
          plugin_stars: yes
          plugin_followup: yes
          plugin_gists: yes
